Taskmaster Netlify Configuration
​Optimized for SPA (Single Page Application) behavior
​[build]
publish = "."
​[[redirects]]
from = "/*"
to = "/index.html"
status = 200
​[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
cache-control = "max-age=0, no-cache, no-store, must-revalidate"
